### PR TITLE
refactor: add return type for prefetch

### PR DESCRIPTION
**Pull request by jmcdo29**
add the return type Promise<any> for the Vue prefetch function for
cleaner development

close issue #241

### What is accomplished by your PR?
description...

Add return type for the VueConstructor.prefetch function to be Promise<any>

### Is there something controversial in your PR?
please take a moment to tell us about your choices...

### Link to the Issue
or a link to a ticket system...
[#241](https://github.com/devCrossNet/vue-starter/issues/241)
# Checklist

### New Feature / Bug Fix

- [X] Run unit tests to ensure all existing tests are still passing
- [ ] Add new passing unit tests to cover the code introduced by your PR
- [X] Add new documentation for the code introduced by your PR

### CODE REVIEW

**Comment by devCrossNet** [comment]
@jmcdo29 thanks for your help!

Can you please remove the package-lock file from the PR? There was no update to the package.json

regards,
Johannes

**Comment by jmcdo29** [comment]
Okay, I think I got it removed correctly.

**Comment by devCrossNet** [comment]
hey @jmcdo29,
unfortunately not. This will delete the package-lock.json from the /next branch.

Can you try to copy the package-lock.json file from the next branch into yours and commit to this branch? 

This should exclude the file from the changeset of the PR (hopefully).

In the end, the file should not appear in the "Files changed" tab.

**Comment by jmcdo29** [comment]
@devCrossNet 
There we go! Sorry for the problems with that!

**Comment by devCrossNet** [comment]
Perfect 👍 it’s all fine 🙂

Thanks for contributing.

**Pull request merged**
