### PR TITLE
feat(progress bar): add progress bar feature

### PR DESCRIPTION
**Pull request by xMartin**
### What is accomplished by your PR?

Adds a progress bar at the top of the window when transitioning between routes.

### Is there something controversial in your PR?

https://github.com/hilongjw/vue-progressbar seems to be the most popular library for that. I'm not so much convinced by the quality of the code. For instance there's a little jump of content when initially loading from the server (https://github.com/hilongjw/vue-progressbar/pull/76). Also the styling is done inline so the question is how to set the colors from the vue-starter theme.

# Checklist

### New Feature / Bug Fix

- [x] Run unit tests to ensure all existing tests are still passing
- [x] Add new passing unit tests to cover the code introduced by your PR
- [ ] Add new documentation for the code introduced by your PR
- [x] Solve jumping content issue (see above)
- [x] Apply theme colors

### CODE REVIEW

**Comment by devCrossNet** [comment]
holy moly, that was fast. will have a look at it asap 👍

**Comment by devCrossNet** [comment]
Can we make our own version? Something like `VueNavigationProgress`?
Otherwise, this would be the first UI component that is a library 😕 

I think we could save a lot of code by removing the `meta` part of this library.
I don't see a use-case for this feature if the code is part of the vue-starter.

**Comment by devCrossNet** [comment]
I think a very simple CSS animated component would be easy to implement and would have the same effect. we could use the same router events in the app component which just sets a property on the progress component (something like `isLoading`). 

Let me know your thoughts.

**Comment by xMartin** [comment]
Yes, makes sense. Thanks for looking into it!

**Comment by xMartin** [comment]
We decided to re-open this with a custom implementation.

**Comment by xMartin** [comment]
I tried to improve the visual appearance but it has a lot of timeouts now ;)

I'd like to set the transition duration from JavaScript, too (instead of CSS), so we don't have duplicated values. 

I didn't look into Story Book, yet.

**Comment by mkirstetter** [comment]
Nuxt has a component for this, might be simpler/better?  —>
https://github.com/nuxt/nuxt.js/blob/dev/lib/app/components/nuxt-loading.vue

**Comment by devCrossNet** [comment]
@xMartin do you want to adapt the next-component somehow or do you want to fix the storybook thing?

I am just asking because I have to rebase the next branch on top of master.

**Comment by xMartin** [comment]
👍 Thanks for catching those!

**Pull request merged**
