### PR TITLE
Allow redirecting from prefetch

### PR DESCRIPTION
**Pull request by xMartin**
### What is accomplished by your PR?
#195 

### Is there something controversial in your PR?
- `router.history` is not in the official typings, maybe considered private?
- The current implementation allows using `router.push` or `router.replace` and handles it behind the scenes. Should we rather be more specific in `prefetch`, something like `return Promise.reject({ code: 302, path: '/path-to-redirect-to'});`?
- Do we want to call `next` in `router.beforeResolve` on the client side in the case of redirecting or not?
- How to best document how to use this? Example redirect in a component or rather a how-to in the docs?
- With the current test setup, I guess we'd need an example implementation to be able to test it with Cypress

# Checklist

### New Feature / Bug Fix

- [x] Run unit tests to ensure all existing tests are still passing
- [ ] Add new passing unit tests to cover the code introduced by your PR
- [ ] Add new documentation for the code introduced by your PR

### CODE REVIEW

**Comment by devCrossNet** [comment]
I added some typings. It can be that they don't want to expose it, but in the source of the router https://github.com/vuejs/vue-router/blob/dev/src/index.js#L28 it's on the same level as exposed attributes of the router - so we just add typings and assume it's a public prob :-)

**Comment by devCrossNet** [comment]
that's a great idea 👍

**Comment by xMartin** [comment]
> let's leave the redirect example from yesterday and add a doc section where we explain that redirects work the same way on the server-side than in the client side. Its exactly the same code, no pitfalls.

Ok. I'd also mention that `router` is passed to `prefetch` specifically for that reason.

**Comment by devCrossNet** [comment]
do you want to make it part of this PR? I think it would be good to have it in this PR

**Comment by xMartin** [comment]
Yes.

**Comment by devCrossNet** [comment]
ok, this PR is the last one for the new version.

I want to release it today or tomorrow.

If you think the docs will take longer I would like to move this PR to the next version and release more often 👍

**Comment by devCrossNet** [comment]
yes, we should test if navigation guards would also work with the current implementation. I guess they will because we support `history.pending`.

I plan to include an auth example in the starter at some point in the future we could update the example then.

what would you suggest? I think it's good enough for the first version of this feature 👍

**Comment by xMartin** [comment]
I opened a bug report with VueRouter because of the redirect issue mentioned above.
https://github.com/vuejs/vue-router/issues/2332

**Pull request merged**
