### PR TITLE
feat(storybook): update storybook

### PR DESCRIPTION
**Pull request by MohitTilwani15**
The 5.0.4 version of storybook brings some useful new features:
1. New design
2. New canvas toolbar to give quick visual access to addons
3. overhauled navigation sidebar with a better menu

In the side panel of storybook, hierarchies of story clusters is not maintained
the fix will close the issue --> https://github.com/devCrossNet/vue-starter/issues/369

### What is accomplished by your PR?

description...

### Is there something controversial in your PR?

please take a moment to tell us about your choices...

### Link to the Issue

or a link to a ticket system...

# Checklist

### New Feature / Bug Fix

- [ ] Run unit tests to ensure all existing tests are still passing
- [ ] Add new passing unit tests to cover the code introduced by your PR
- [ ] Change documentation for the code introduced by your PR
- [ ] Add Story / Design System Page for a new component introduced by your PR

### CODE REVIEW

**Comment by MohitTilwani15** [comment]
@devCrossNet This PR can be merged when vue starter has updated version of @vuesion/service with the updated storybook.

**Comment by devCrossNet** [comment]
@MohitTilwani15 can you rebase this branch on `next`?

would the update to the new vuesion/service break the existing vue-starter without merging this PR? That's something I have to know before releasing the vuesion/service

**Comment by MohitTilwani15** [comment]
would the update to the new vuesion/service break the existing vue-starter without merging this PR?  -- Yes

I did the rebase as asked by you

**Comment by devCrossNet** [comment]
ok then we have to release a major version in vuesion/service

**Comment by MohitTilwani15** [comment]
okay

**Comment by MohitTilwani15** [comment]
> LGTM 👍
> 
> can you already update the @vuesion/service to version `^2.0.0` in the package.json?
> 
> I will publish this package asap.

Have you published @vuesion/service 2.0.0 
I think @vuesion/service should be published first and then only I cant install the new module, as package-lock.json also needs to be updated

**Comment by devCrossNet** [comment]
You’re right, I will let you know 👍

**Comment by devCrossNet** [comment]
@MohitTilwani15 I published `@vuesion/service@2.0.0-alpha.0`

**Comment by MohitTilwani15** [comment]
> @MohitTilwani15 I published `@vuesion/service@2.0.0-alpha.0`

Update the @vuesion/service version

**Comment by devCrossNet** [comment]
@MohitTilwani15 the `npm run storybook:build` command seems not to work in the ci. can you run it locally and see what the issue is?

**Comment by MohitTilwani15** [comment]
> @MohitTilwani15 the `npm run storybook:build` command seems not to work in the ci. can you run it locally and see what the issue is?

It works fine locally. Though there are some warnings about vendors asset size limit. Could that be the issue?

**Comment by devCrossNet** [comment]
no, that's just the webpack performance budget, nothing to worry about. ok, I'll merge it and test it in the next branch 👍

**Pull request merged**
